image: node:latest

stages:
  - test
  - deploy

test-package:
  stage: test
  script:
    - npm install --include=dev
    - npm test
  tags:
    - test

publish-npm:
  stage: deploy
  dependencies:
    - test-package
  script:
    - echo "@scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  only:
    - master
    - main
  tags:
    - build
