image: node:20
cache:
  paths:
    - .npm/
    - node_modules/
    - .npmrc

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - setup
  - test
  - deploy

setup:
  tags:
    - setup
  stage: setup
  script:
    - npm ci --cache .npm --prefer-offline
    - |
      export NPM_PROJECT_URL=$(echo "$CI_PROJECT_URL" | sed "s/${CI_PROJECT_PATH//\//\\/}/api\/v4/g")
      export NPM_REGISTRY_PATHS=$(echo "$CI_PROJECT_URL" | sed "s/${CI_PROJECT_PATH//\//\\/}/api\/v4/g")
      export NPMRC_URL=$(echo "$NPM_REGISTRY_PATHS" |  sed 's/[^:]*[:]//')
      export NPMRC_INSTALL_URL=$(echo "$NPMRC_URL/packages/npm/:_authToken=$OAUTH_TOKEN")
      export NPMRC_PUBLISH_URL=$(echo "$NPMRC_URL/projects/$CI_PROJECT_ID/packages/npm/:_authToken=$OAUTH_TOKEN")
      export NPM_SCOPE=$(echo "$CI_PROJECT_PATH" | sed 's/[/].*$//')
      echo "@$NPM_SCOPE:registry=$NPM_REGISTRY_PATHS/npm/" >> .npmrc
      echo "$NPMRC_INSTALL_URL" >> .npmrc
      echo "$NPMRC_PUBLISH_URL" >> .npmrc

test-package:
  stage: test
  script:
    - npm run test:ci --cache .npm
  tags:
    - test
  dependencies:
    - setup
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

publish-npm:
  stage: deploy
  dependencies:
    - test-package
    - setup
  script:
    - cat .npmrc
    - npm run semantic-release --cache .npm
  only:
    - main
  tags:
    - build
