default:
  image: node:20
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  script:
    - npm ci --include=dev
  tags:
    - setup
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test-package:
  stage: test
  script:
    - npm run test:ci
  tags:
    - test
  dependencies:
    - setup
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

publish-npm:
  stage: deploy
  dependencies:
    - test-package
    - setup
  script:
    - npm run semantic-release
  only:
    - main
  tags:
    - build
