default:
  image: node:20
  cache:
    key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
    - node_modules/
    - .npmrc

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - setup
  - test
  - deploy

setup:
  tags:
    - setup
  stage: setup
  script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
      echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
      echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      echo 
      } | tee -a .npmrc

test-package:
  stage: test
  script:
    - npm run test:ci --cache .npm
  tags:
    - test
  dependencies:
    - setup
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

publish-npm:
  stage: deploy
  dependencies:
    - test-package
    - setup
  script:
    - cat .npmrc
    - npm run semantic-release --cache .npm
  only:
    - main
  tags:
    - build
