image: node:latest

stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  script:
    - npm ci --include=dev
  tags:
    - setup
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test-package:
  stage: test
  image: node:20
  script:
    - npm run test:ci
  tags:
    - test
  dependencies:
    - setup
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

publish-npm:
  stage: deploy
  dependencies:
    - test-package
    - setup
  script:
    - npm run semantic-release
  only:
    - main
  tags:
    - build
